displayName: CouchDB Proxy
summary: Authenticates requests with JWTs and authorizes access to CouchDB databases, forwarding credentials via proxy authentication headers
iconPath: .github/assets/icon.png
type: middleware
import: github.com/deep-rent/traefik-plugin-couchdb
testData:
  jwks: https://auth.example.com/.well-known/jwks.json
  secret: NyH2b4ltJ1l3wRnuQXgH7Fnrl7PKzYQH
  lifetime: 600
  issuer: https://auth.example.com/
  audience: ['couchdb-api']
  strict: true
  leeway: 60
  algorithms: [ES256, ES384, ES512]
  rules:
    - when: 'C["sub"] == "bob"'
      mode: deny
    - when: 'true'
      mode: allow
