name: vouch-stack

services:
  couchdb:
    build:
      context: ./container/couchdb
      dockerfile: Dockerfile
    container_name: couchdb
    restart: unless-stopped
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./container/couchdb/local.ini:/tmp/configs/local.ini:ro
    entrypoint: /usr/local/bin/entrypoint-wrapper.sh

  auth:
    image: nginx:alpine
    container_name: auth
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./container/auth:/usr/share/nginx/html/.well-known:ro
  vouch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
    container_name: vouch
    depends_on:
      - auth
      - couchdb
    environment:
      VOUCH_LOG: info
    volumes:
      - ./container/vouch/config.yaml:/app/config.yaml:ro
      - ./container/vouch/jwks.json:/app/jwks.json:ro
    ports:
      - "8080:8080"

volumes:
  couchdb-data:

networks:
  default:
    name: vouch-net
