apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vouch
  namespace: data
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  rules:
    - host: couchdb.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vouch
                port:
                  number: 80
