http:
  middlewares:
    couchdb-auth:
      plugin:
        traefik-plugin-couchdb:
          jwks: http://auth/jwks.json
          issuer: nginx
          audience: couchdb
          proxySecret: changeme
          rules:
            - when: 'true'
              mode: allow
              user: '"alice"'
              role: '["reader"]'
