log:
  level: INFO

experimental:
  localPlugins:
    traefik-plugin-couchdb:
      moduleName: github.com/deep-rent/traefik-plugin-couchdb

entryPoints:
  web:
    address: ":80"

providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic.yml
